import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const finalContexts: Record<string, Record<number, string>> = {
  'excel-logistica': {
    1: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>📦 Ponto de Pedido</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="padding:15px;background:#FFF3CD;border:3px solid #FFA000;border-radius:8px;margin:20px 0"><div style="font-size:18px;font-weight:bold;text-align:center;margin-bottom:10px">Fórmula do Ponto de Pedido</div><div style="text-align:center;font-size:16px;background:#fff;padding:12px;border-radius:4px;margin-top:10px"><code style="color:#2196F3;font-weight:bold">PP = (Demanda Diária × Lead Time) + Estoque de Segurança</code></div></div><div style="padding:15px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>💡 Quando o estoque atingir o Ponto de Pedido, é hora de fazer um novo pedido!</strong><p style="margin:10px 0 0 0;font-size:14px;color:#555">Isso garante que não falte produto durante o lead time de entrega</p></div></div></div>',
    
    3: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>📊 Curva ABC</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Curva ABC</strong> classifica produtos por importância:</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0"><div style="padding:15px;background:#4CAF50;color:white;border-radius:8px;text-align:center"><strong>Classe A</strong><div style="margin-top:10px;font-size:24px;font-weight:bold">80%</div><div style="font-size:12px">do faturamento</div><div style="margin-top:5px;font-size:14px">20% dos itens</div></div><div style="padding:15px;background:#FF9800;color:white;border-radius:8px;text-align:center"><strong>Classe B</strong><div style="margin-top:10px;font-size:24px;font-weight:bold">15%</div><div style="font-size:12px">do faturamento</div><div style="margin-top:5px;font-size:14px">30% dos itens</div></div><div style="padding:15px;background:#F44336;color:white;border-radius:8px;text-align:center"><strong>Classe C</strong><div style="margin-top:10px;font-size:24px;font-weight:bold">5%</div><div style="font-size:12px">do faturamento</div><div style="margin-top:5px;font-size:14px">50% dos itens</div></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>💡 Use a Curva ABC para:</strong> Priorizar gestão dos itens mais importantes (Classe A)</div></div></div>',
    
    6: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>⏱️ Lead Time</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="margin:20px 0"><div style="text-align:center;font-size:16px;margin-bottom:20px"><strong>Linha do Tempo do Lead Time:</strong></div><div style="display:flex;align-items:center;justify-content:space-between;padding:20px;background:#E3F2FD;border-radius:8px"><div style="text-align:center"><div style="width:60px;height:60px;background:#2196F3;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;margin:0 auto 10px">📝</div><strong>Pedido</strong><div style="font-size:12px;color:#666;margin-top:5px">Dia 0</div></div><div style="flex:1;height:4px;background:#2196F3;margin:0 10px"></div><div style="text-align:center"><div style="width:60px;height:60px;background:#4CAF50;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:24px;margin:0 auto 10px">📦</div><strong>Entrega</strong><div style="font-size:12px;color:#666;margin-top:5px">Dia 7</div></div></div><div style="text-align:center;margin-top:15px;padding:10px;background:#FFE082;border-radius:4px"><strong>Lead Time = 7 dias</strong></div></div><div style="padding:12px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px;margin-top:15px"><strong>💡 Lead Time</strong> é o tempo entre fazer o pedido e receber a mercadoria</div></div></div>',
    
    8: '<div style="padding:20px;background:linear-gradient(135deg,#4facfe,#00f2fe);border-radius:12px;color:white"><h3>🔍 PROCV para Pedidos</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>PROCV no controle de pedidos:</strong></p><div style="background:#f5f5f5;padding:15px;border-radius:4px;margin:15px 0"><strong>Cenário:</strong> Você tem um pedido com código do produto e quer buscar o nome e preço automaticamente<br><br><code style="display:block;background:#fff;padding:10px;border-radius:4px;margin-top:10px;color:#2196F3">=PROCV(codigo_produto, tabela_produtos, 2, FALSO)</code></div><div style="padding:12px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>✅ Benefícios:</strong><ul style="margin:10px 0;padding-left:20px;font-size:14px"><li>Evita digitação manual</li><li>Reduz erros</li><li>Agiliza preenchimento de pedidos</li></ul></div></div></div>',
    
    9: '<div style="padding:20px;background:linear-gradient(135deg,#a8edea,#fed6e3);border-radius:12px"><h3>🛡️ Estoque de Segurança</h3><div style="background:white;padding:20px;border-radius:8px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:15px;background:#FFEBEE;border-left:4px solid #F44336;border-radius:4px"><div style="text-align:center;font-size:32px;margin-bottom:10px">⚠️</div><strong style="color:#C62828">Sem Estoque de Segurança</strong><p style="font-size:13px;margin-top:10px;color:#666">Qualquer imprevisto causa ruptura (falta de produto)</p></div><div style="padding:15px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px"><div style="text-align:center;font-size:32px;margin-bottom:10px">✅</div><strong style="color:#2E7D32">Com Estoque de Segurança</strong><p style="font-size:13px;margin-top:10px;color:#666">Proteção contra variações de demanda e atrasos</p></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>💡 Estoque de Segurança</strong> = quantidade extra mantida para imprevistos</div></div></div>',
  },
  
  'excel-financas': {
    1: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>💰 Fluxo de Caixa</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="margin:20px 0"><strong style="display:block;margin-bottom:15px">Exemplo de Fluxo de Caixa:</strong><div style="background:#f5f5f5;padding:15px;border-radius:4px"><div style="display:flex;justify-content:space-between;padding:10px;background:#E8F5E9;border-left:4px solid #4CAF50;margin-bottom:10px"><span><strong>Entradas (Receitas)</strong></span><span style="color:#4CAF50;font-weight:bold">+ R$ 15.000</span></div><div style="display:flex;justify-content:space-between;padding:10px;background:#FFEBEE;border-left:4px solid #F44336;margin-bottom:10px"><span><strong>Saídas (Despesas)</strong></span><span style="color:#F44336;font-weight:bold">- R$ 8.000</span></div><div style="display:flex;justify-content:space-between;padding:15px;background:#E3F2FD;border-left:4px solid #2196F3;font-size:18px;font-weight:bold"><span>Saldo Final</span><span style="color:#2196F3">= R$ 7.000</span></div></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>💡 Fluxo de Caixa</strong> controla todo dinheiro que entra e sai da empresa/pessoa</div></div></div>',
    
    5: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>💳 Função PGTO</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>PGTO</strong> calcula o valor da prestação de um empréstimo:</p><div style="background:#E3F2FD;padding:15px;border-radius:4px;margin:15px 0"><code style="display:block;font-size:15px;color:#1976D2;margin-bottom:10px">=PGTO(taxa, nper, vp)</code><br><strong>Exemplo:</strong> Empréstimo de R$ 10.000<br>Taxa: 1% ao mês<br>Prazo: 12 meses<br><br><code style="display:block;background:#fff;padding:10px;border-radius:4px;margin-top:10px;color:#2196F3">=PGTO(1%, 12, -10000) = R$ 888,49</code></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>⚠️ Atenção:</strong> O valor presente (vp) deve ser negativo!</div></div></div>',
    
    7: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>📊 DRE (Demonstração do Resultado)</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="background:#f5f5f5;padding:15px;border-radius:4px;margin:15px 0"><div style="padding:10px;margin:5px 0"><strong>Receita Bruta</strong><span style="float:right">R$ 100.000</span></div><div style="padding:10px;margin:5px 0;color:#F44336"><strong>(-) Deduções/Impostos</strong><span style="float:right">R$ 15.000</span></div><div style="padding:10px;margin:5px 0;background:#E3F2FD;font-weight:bold"><strong>= Receita Líquida</strong><span style="float:right">R$ 85.000</span></div><div style="padding:10px;margin:5px 0;color:#F44336"><strong>(-) Custos e Despesas</strong><span style="float:right">R$ 60.000</span></div><div style="padding:15px;margin:10px 0;background:#E8F5E9;font-weight:bold;font-size:18px;border-left:4px solid #4CAF50"><strong>= Lucro Líquido</strong><span style="float:right;color:#4CAF50">R$ 25.000</span></div></div><div style="padding:12px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>📌 DRE</strong> mostra se a empresa teve lucro ou prejuízo no período</div></div></div>',
    
    9: '<div style="padding:20px;background:linear-gradient(135deg,#4facfe,#00f2fe);border-radius:12px;color:white"><h3>📈 VPL (Valor Presente Líquido)</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>VPL</strong> avalia se um investimento vale a pena:</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0"><div style="padding:20px;background:#E8F5E9;border:3px solid #4CAF50;border-radius:8px;text-align:center"><div style="font-size:32px;margin-bottom:10px">✅</div><strong>VPL > 0</strong><p style="font-size:13px;margin-top:10px;color:#666">Investimento VALE A PENA</p></div><div style="padding:20px;background:#FFF3CD;border:3px solid #FFA000;border-radius:8px;text-align:center"><div style="font-size:32px;margin-bottom:10px">⚖️</div><strong>VPL = 0</strong><p style="font-size:13px;margin-top:10px;color:#666">Investimento NEUTRO</p></div><div style="padding:20px;background:#FFEBEE;border:3px solid #F44336;border-radius:8px;text-align:center"><div style="font-size:32px;margin-bottom:10px">❌</div><strong>VPL < 0</strong><p style="font-size:13px;margin-top:10px;color:#666">Investimento NÃO VALE A PENA</p></div></div><div style="padding:12px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>💡 Fórmula Excel:</strong> <code>=VPL(taxa, fluxos) + investimento_inicial</code></div></div></div>',
  },
  
  'produtividade-excel': {
    1: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>⌨️ Atalhos Essenciais</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:15px;margin:15px 0"><div style="padding:15px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><kbd style="background:#fff;padding:5px 10px;border-radius:4px;border:2px solid #2196F3;font-weight:bold;font-size:16px">Ctrl + A</kbd><p style="margin:10px 0 0 0;font-size:14px">Selecionar tudo</p></div><div style="padding:15px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px"><kbd style="background:#fff;padding:5px 10px;border-radius:4px;border:2px solid #4CAF50;font-weight:bold;font-size:16px">Ctrl + C</kbd><p style="margin:10px 0 0 0;font-size:14px">Copiar</p></div><div style="padding:15px;background:#FCE4EC;border-left:4px solid #E91E63;border-radius:4px"><kbd style="background:#fff;padding:5px 10px;border-radius:4px;border:2px solid #E91E63;font-weight:bold;font-size:16px">Ctrl + V</kbd><p style="margin:10px 0 0 0;font-size:14px">Colar</p></div><div style="padding:15px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><kbd style="background:#fff;padding:5px 10px;border-radius:4px;border:2px solid #FFA000;font-weight:bold;font-size:16px">Ctrl + Z</kbd><p style="margin:10px 0 0 0;font-size:14px">Desfazer</p></div></div></div></div>',
    
    2: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>🚀 Navegação Rápida</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="margin:20px 0;text-align:center"><p style="margin-bottom:20px"><strong>Pular para a última célula com dados:</strong></p><div style="display:inline-flex;align-items:center;gap:15px;padding:20px;background:#E3F2FD;border-radius:8px"><kbd style="background:#fff;padding:10px 15px;border-radius:4px;border:3px solid #2196F3;font-weight:bold;font-size:18px">Ctrl</kbd><span style="font-size:24px">+</span><div style="display:flex;flex-direction:column;gap:5px"><div style="display:flex;gap:5px"><kbd style="background:#fff;padding:8px;border-radius:4px;border:2px solid #2196F3;width:35px;height:35px;display:flex;align-items:center;justify-content:center">↑</kbd></div><div style="display:flex;gap:5px"><kbd style="background:#fff;padding:8px;border-radius:4px;border:2px solid #2196F3;width:35px;height:35px;display:flex;align-items:center;justify-content:center">←</kbd><kbd style="background:#fff;padding:8px;border-radius:4px;border:2px solid #2196F3;width:35px;height:35px;display:flex;align-items:center;justify-content:center">↓</kbd><kbd style="background:#fff;padding:8px;border-radius:4px;border:2px solid #2196F3;width:35px;height:35px;display:flex;align-items:center;justify-content:center">→</kbd></div></div></div></div><div style="padding:12px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px;margin-top:15px"><strong>💡 Super útil</strong> para planilhas grandes!</div></div></div>',
    
    3: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>↩️ Desfazer e Refazer</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:20px 0"><div style="padding:20px;background:#FFEBEE;border:3px solid #F44336;border-radius:8px;text-align:center"><div style="font-size:48px;margin-bottom:15px">↩️</div><kbd style="background:#fff;padding:10px 15px;border-radius:4px;border:2px solid #F44336;font-weight:bold;font-size:18px">Ctrl + Z</kbd><p style="margin:15px 0 0 0;font-weight:bold">Desfazer</p><p style="font-size:13px;color:#666;margin-top:5px">Volta a ação anterior</p></div><div style="padding:20px;background:#E8F5E9;border:3px solid #4CAF50;border-radius:8px;text-align:center"><div style="font-size:48px;margin-bottom:15px">↪️</div><kbd style="background:#fff;padding:10px 15px;border-radius:4px;border:2px solid #4CAF50;font-weight:bold;font-size:18px">Ctrl + Y</kbd><p style="margin:15px 0 0 0;font-weight:bold">Refazer</p><p style="font-size:13px;color:#666;margin-top:5px">Refaz ação desfeita</p></div></div></div></div>',
    
    4: '<div style="padding:20px;background:linear-gradient(135deg,#4facfe,#00f2fe);border-radius:12px;color:white"><h3>⚡ Flash Fill (Preenchimento Relâmpago)</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Flash Fill</strong> detecta padrões e preenche automaticamente:</p><div style="background:#f5f5f5;padding:15px;border-radius:4px;margin:15px 0"><div style="display:grid;grid-template-columns:1fr 2fr;gap:10px"><div style="font-weight:bold;padding:8px;background:#E3F2FD;border-radius:4px">Você digita:</div><div style="font-weight:bold;padding:8px;background:#E8F5E9;border-radius:4px">Excel preenche:</div><div style="padding:8px">João Silva</div><div style="padding:8px;color:#999">João</div><div style="padding:8px">Maria Santos</div><div style="padding:8px;color:#999">Maria</div><div style="padding:8px;color:#2196F3;font-weight:bold">Pedro Costa</div><div style="padding:8px;color:#4CAF50;font-weight:bold">Pedro ← (automático!)</div></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>⚡ Atalho:</strong> <kbd style="background:#fff;padding:3px 8px;border:1px solid #ccc;border-radius:3px">Ctrl + E</kbd></div></div></div>',
    
    5: '<div style="padding:20px;background:linear-gradient(135deg,#a8edea,#fed6e3);border-radius:12px"><h3>📋 Colar Especial</h3><div style="background:white;padding:20px;border-radius:8px"><p style="margin-bottom:15px"><strong>Colar Especial</strong> permite colar apenas o que você quer:</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:15px 0"><div style="padding:15px;background:#E3F2FD;border-radius:4px;text-align:center"><div style="font-size:24px;margin-bottom:10px">🔢</div><strong>Apenas Valores</strong><p style="font-size:12px;color:#666;margin-top:8px">Remove fórmulas</p></div><div style="padding:15px;background:#E8F5E9;border-radius:4px;text-align:center"><div style="font-size:24px;margin-bottom:10px">🎨</div><strong>Apenas Formato</strong><p style="font-size:12px;color:#666;margin-top:8px">Copia cores/bordas</p></div><div style="padding:15px;background:#FCE4EC;border-radius:4px;text-align:center"><div style="font-size:24px;margin-bottom:10px">📐</div><strong>Transpor</strong><p style="font-size:12px;color:#666;margin-top:8px">Linhas ↔ Colunas</p></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>📌 Atalho:</strong> <kbd style="background:#fff;padding:3px 8px;border:1px solid #ccc;border-radius:3px">Ctrl + Alt + V</kbd></div></div></div>',
    
    6: '<div style="padding:20px;background:linear-gradient(135deg,#ffecd2,#fcb69f);border-radius:12px"><h3>➕ Inserir Linha Rapidamente</h3><div style="background:white;padding:20px;border-radius:8px"><div style="text-align:center;margin:20px 0"><p style="margin-bottom:20px;font-size:16px"><strong>3 formas de inserir linha:</strong></p><div style="display:inline-block;text-align:left;background:#f5f5f5;padding:20px;border-radius:8px"><div style="margin:10px 0;padding:10px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>1️⃣ Atalho rápido:</strong><br><kbd style="background:#fff;padding:5px 10px;margin-top:8px;display:inline-block;border-radius:4px;border:2px solid #2196F3">Ctrl + +</kbd></div><div style="margin:10px 0;padding:10px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px"><strong>2️⃣ Menu contexto:</strong><br>Botão direito → Inserir</div><div style="margin:10px 0;padding:10px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>3️⃣ Faixa de opções:</strong><br>Aba Página Inicial → Inserir</div></div></div></div></div>',
    
    7: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>🔍 Localizar e Substituir</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:20px;background:#E3F2FD;border-radius:8px;text-align:center"><div style="font-size:40px;margin-bottom:10px">🔍</div><strong>Localizar</strong><br><kbd style="background:#fff;padding:8px 15px;margin-top:10px;display:inline-block;border-radius:4px;border:2px solid #2196F3;font-weight:bold">Ctrl + L</kbd><p style="font-size:13px;color:#666;margin-top:10px">Encontra texto/valor</p></div><div style="padding:20px;background:#E8F5E9;border-radius:8px;text-align:center"><div style="font-size:40px;margin-bottom:10px">🔄</div><strong>Substituir</strong><br><kbd style="background:#fff;padding:8px 15px;margin-top:10px;display:inline-block;border-radius:4px;border:2px solid #4CAF50;font-weight:bold">Ctrl + U</kbd><p style="font-size:13px;color:#666;margin-top:10px">Substitui em massa</p></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>💡 Exemplo:</strong> Substituir "Produto A" por "Item X" em toda a planilha de uma vez</div></div></div>',
    
    8: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>❄️ Congelar Painéis</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="margin:20px 0"><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin-bottom:15px"><strong>Sem Congelar:</strong><br><span style="font-size:13px;color:#666">Ao rolar a tela, os cabeçalhos somem e você não sabe mais o que cada coluna significa 😰</span></div><div style="background:#E8F5E9;padding:15px;border-radius:8px;border-left:4px solid #4CAF50"><strong>Com Congelar:</strong><br><span style="font-size:13px;color:#666">Os cabeçalhos ficam sempre visíveis, não importa quantas linhas você role! 🎉</span></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>📌 Como congelar:</strong><br>Clique na linha abaixo do que quer congelar → Aba Exibir → Congelar Painéis</div></div></div>',
    
    10: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>🚀 Preenchimento Rápido</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Alça de Preenchimento</strong> = Quadradinho no canto da célula:</p><div style="text-align:center;margin:20px 0"><div style="display:inline-block;padding:20px;background:#E3F2FD;border:3px solid #2196F3;border-radius:8px;position:relative"><div style="padding:15px 25px;background:white;border:2px solid #666;border-radius:4px;font-weight:bold">Segunda</div><div style="position:absolute;bottom:15px;right:15px;width:12px;height:12px;background:#2196F3;border:2px solid #fff;cursor:move"></div></div><div style="margin:15px 0;font-size:24px">⬇️ Arraste</div><div style="display:inline-block;padding:10px;background:#E8F5E9;border-radius:4px;border:2px solid #4CAF50"><div style="padding:8px 20px;margin:2px;background:white;border:1px solid #ddd;border-radius:4px">Segunda</div><div style="padding:8px 20px;margin:2px;background:white;border:1px solid #ddd;border-radius:4px">Terça</div><div style="padding:8px 20px;margin:2px;background:white;border:1px solid #ddd;border-radius:4px">Quarta</div><div style="padding:8px 20px;margin:2px;background:white;border:1px solid #ddd;border-radius:4px">Quinta</div></div></div></div></div>',
  },
  
  'excel-avancado': {
    1: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>📊 Tabela Dinâmica</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Tabela Dinâmica</strong> resume grandes volumes de dados:</p><div style="background:#f5f5f5;padding:15px;border-radius:4px;margin:15px 0"><strong>De milhares de linhas:</strong><div style="font-size:12px;color:#666;margin:10px 0;font-family:monospace">Produto | Vendedor | Valor<br>Mouse | Ana | 50<br>Mouse | Bruno | 60<br>Teclado | Ana | 150<br>...</div></div><div style="font-size:24px;text-align:center;margin:15px 0">⬇️</div><div style="background:#E8F5E9;padding:15px;border-radius:4px;border-left:4px solid #4CAF50"><strong>Para resumo simples:</strong><div style="margin-top:10px"><strong>Total por Produto:</strong><br>Mouse: R$ 110<br>Teclado: R$ 150</div></div></div></div>',
    
    2: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>🔄 Atualizar Tabela Dinâmica</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Tabelas Dinâmicas NÃO atualizam automaticamente!</strong></p><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:20px;background:#FFEBEE;border-left:4px solid #F44336;border-radius:4px;text-align:center"><div style="font-size:40px;margin-bottom:10px">❌</div><strong>Problema:</strong><p style="font-size:13px;color:#666;margin-top:10px">Você adiciona dados novos mas a tabela dinâmica não reflete</p></div><div style="padding:20px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px;text-align:center"><div style="font-size:40px;margin-bottom:10px">✅</div><strong>Solução:</strong><p style="font-size:13px;color:#666;margin-top:10px">Clique direito → Atualizar</p></div></div><div style="padding:12px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>⚡ Ou pressione:</strong> <kbd style="background:#fff;padding:5px 10px;border:1px solid #ccc;border-radius:3px">Alt + F5</kbd></div></div></div>',
    
    3: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>🆚 PROCX vs PROCV</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:15px;background:#FFEBEE;border:3px solid #F44336;border-radius:8px"><div style="text-align:center;margin-bottom:10px"><strong>PROCV</strong></div><ul style="font-size:13px;padding-left:20px;color:#666"><li>❌ Busca só à direita</li><li>❌ Precisa do número da coluna</li><li>❌ Lenta em tabelas grandes</li><li>❌ Quebra se adicionar colunas</li></ul></div><div style="padding:15px;background:#E8F5E9;border:3px solid #4CAF50;border-radius:8px"><div style="text-align:center;margin-bottom:10px"><strong>PROCX</strong></div><ul style="font-size:13px;padding-left:20px;color:#666"><li>✅ Busca em qualquer direção</li><li>✅ Usa nome da coluna</li><li>✅ Muito mais rápida</li><li>✅ Não quebra se mover colunas</li></ul></div></div><div style="padding:12px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px"><strong>🚀 PROCX</strong> é a evolução do PROCV (Excel 365+)</div></div></div>',
    
    5: '<div style="padding:20px;background:linear-gradient(135deg,#4facfe,#00f2fe);border-radius:12px;color:white"><h3>⚡ Power Query</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Power Query</strong> é uma ferramenta de ETL (Extrair, Transformar, Carregar):</p><div style="display:flex;align-items:center;justify-content:space-between;gap:15px;margin:20px 0;flex-wrap:wrap"><div style="flex:1;padding:15px;background:#E3F2FD;border-radius:8px;text-align:center;min-width:150px"><div style="font-size:32px;margin-bottom:10px">📥</div><strong>Extrair</strong><p style="font-size:12px;color:#666;margin-top:8px">Importar de várias fontes</p></div><div style="font-size:24px">→</div><div style="flex:1;padding:15px;background:#FFF3CD;border-radius:8px;text-align:center;min-width:150px"><div style="font-size:32px;margin-bottom:10px">🔧</div><strong>Transformar</strong><p style="font-size:12px;color:#666;margin-top:8px">Limpar e formatar</p></div><div style="font-size:24px">→</div><div style="flex:1;padding:15px;background:#E8F5E9;border-radius:8px;text-align:center;min-width:150px"><div style="font-size:32px;margin-bottom:10px">📤</div><strong>Carregar</strong><p style="font-size:12px;color:#666;margin-top:8px">Trazer para o Excel</p></div></div></div></div>',
    
    6: '<div style="padding:20px;background:linear-gradient(135deg,#a8edea,#fed6e3);border-radius:12px"><h3>🔢 Matrizes Dinâmicas</h3><div style="background:white;padding:20px;border-radius:8px"><p style="margin-bottom:15px"><strong>Fórmulas que expandem automaticamente:</strong></p><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin:15px 0"><code style="display:block;font-size:14px;color:#1976D2;margin-bottom:10px">=A1:A5 * 2</code><br><strong>Antes (Excel antigo):</strong><br><span style="font-size:12px;color:#666">Você precisava arrastar a fórmula</span><br><br><strong>Agora (Excel 365):</strong><br><span style="font-size:12px;color:#666">A fórmula expande sozinha para 5 células! ✨</span></div><div style="padding:12px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px"><strong>💡 Spill Range:</strong> Quando uma fórmula "derrama" em várias células</div></div></div>',
    
    8: '<div style="padding:20px;background:linear-gradient(135deg,#ffecd2,#fcb69f);border-radius:12px"><h3>🧬 LAMBDA (Funções Personalizadas)</h3><div style="background:white;padding:20px;border-radius:8px"><p style="margin-bottom:15px"><strong>LAMBDA</strong> cria suas próprias funções reutilizáveis:</p><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin:15px 0"><strong>Exemplo: Calcular IMC</strong><br><code style="display:block;font-size:13px;color:#1976D2;margin:10px 0">=LAMBDA(peso, altura, peso/(altura^2))</code><br><span style="font-size:12px;color:#666">Depois você pode usar: <code>=IMC(75, 1.75)</code></span></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>✅ Vantagens:</strong><ul style="margin:10px 0;padding-left:20px;font-size:14px"><li>Reutilizável</li><li>Mais legível</li><li>Facilita manutenção</li></ul></div></div></div>',
    
    9: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>🎛️ Segmentação em Tabela Dinâmica</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>Slicers</strong> são botões visuais para filtrar rapidamente:</p><div style="display:inline-block;padding:15px;background:#f5f5f5;border:2px solid #2196F3;border-radius:8px;margin:15px auto"><div style="padding:10px;background:#2196F3;color:white;font-weight:bold;border-radius:4px 4px 0 0">Ano</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:10px"><button style="padding:10px;background:white;border:2px solid #ddd;border-radius:4px">2021</button><button style="padding:10px;background:white;border:2px solid #ddd;border-radius:4px">2022</button><button style="padding:10px;background:#4CAF50;color:white;border:none;border-radius:4px;font-weight:bold">2023</button><button style="padding:10px;background:white;border:2px solid #ddd;border-radius:4px">2024</button></div></div><div style="padding:12px;background:#E3F2FD;border-left:4px solid #2196F3;border-radius:4px;margin-top:15px"><strong>✅ Muito mais fácil</strong> do que usar filtros tradicionais!</div></div></div>',
  },
  
  'excel-ia': {
    1: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>🤖 IA para Criar Fórmulas</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin:15px 0"><strong>Você escreve em português:</strong><div style="background:white;padding:12px;border-radius:4px;margin:10px 0;border-left:4px solid #2196F3">"Quero somar todos os valores da coluna A onde a coluna B é maior que 100"</div></div><div style="font-size:24px;text-align:center;margin:15px 0">⬇️ IA traduz ⬇️</div><div style="background:#E8F5E9;padding:15px;border-radius:8px;border-left:4px solid #4CAF50"><strong>Fórmula pronta:</strong><code style="display:block;background:white;padding:12px;border-radius:4px;margin-top:10px;color:#2196F3;font-weight:bold">=SOMASE(B:B,">100",A:A)</code></div></div></div>',
    
    2: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>💬 Prompt Eficiente para Excel</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:15px;background:#FFEBEE;border-left:4px solid #F44336;border-radius:4px"><div style="text-align:center;font-size:24px;margin-bottom:10px">❌</div><strong>Prompt Ruim:</strong><div style="margin-top:10px;font-size:13px;color:#666;background:#fff;padding:10px;border-radius:4px">"Crie uma fórmula"</div></div><div style="padding:15px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px"><div style="text-align:center;font-size:24px;margin-bottom:10px">✅</div><strong>Prompt Bom:</strong><div style="margin-top:10px;font-size:13px;color:#666;background:#fff;padding:10px;border-radius:4px">"Crie uma fórmula que calcule o total de vendas (coluna C) apenas para o vendedor João (coluna A) em 2024 (coluna B)"</div></div></div><div style="padding:12px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px"><strong>📌 Seja específico:</strong> Mencione colunas, condições e o resultado esperado</div></div></div>',
    
    3: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>🔍 IA Explica Fórmulas Complexas</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="background:#f5f5f5;padding:15px;border-radius:8px;margin:15px 0"><strong>Fórmula misteriosa:</strong><code style="display:block;background:white;padding:12px;border-radius:4px;margin:10px 0;color:#2196F3;font-size:13px;overflow-x:auto">=SOMASE(SE(MÊS(A:A)=1;B:B))</code></div><div style="font-size:24px;text-align:center;margin:15px 0">⬇️ IA explica ⬇️</div><div style="background:#E3F2FD;padding:15px;border-radius:8px;border-left:4px solid #2196F3"><strong>Explicação clara:</strong><p style="margin:10px 0;font-size:14px;color:#555">"Esta fórmula soma todos os valores da coluna B, mas apenas das linhas onde a data na coluna A é de Janeiro (mês 1)"</p></div></div></div>',
    
    4: '<div style="padding:20px;background:linear-gradient(135deg,#4facfe,#00f2fe);border-radius:12px;color:white"><h3>📊 IA para Automatizar Análises</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>IA pode gerar análises completas:</strong></p><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin:15px 0"><strong>Você pede:</strong><div style="background:white;padding:10px;border-radius:4px;margin:10px 0;font-size:14px">"Analise estas vendas e me dê insights sobre o melhor produto"</div></div><div style="background:#E8F5E9;padding:15px;border-radius:8px;border-left:4px solid #4CAF50;margin-top:15px"><strong>IA entrega:</strong><ul style="padding-left:20px;font-size:14px;margin:10px 0"><li>✅ Tabela Dinâmica criada</li><li>✅ Gráficos gerados</li><li>✅ Insights escritos</li><li>✅ Recomendações práticas</li></ul></div></div></div>',
    
    5: '<div style="padding:20px;background:linear-gradient(135deg,#a8edea,#fed6e3);border-radius:12px"><h3>✅ Validar Fórmulas com IA</h3><div style="background:white;padding:20px;border-radius:8px"><p style="margin-bottom:15px"><strong>IA verifica se sua fórmula está correta:</strong></p><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:15px;background:#FFEBEE;border-radius:8px"><div style="font-size:32px;text-align:center;margin-bottom:10px">🐛</div><strong>Sua fórmula:</strong><code style="display:block;background:white;padding:10px;border-radius:4px;margin:10px 0;font-size:12px">=SOMA(A1;A10)</code></div><div style="padding:15px;background:#E8F5E9;border-radius:8px"><div style="font-size:32px;text-align:center;margin-bottom:10px">✅</div><strong>IA corrige:</strong><code style="display:block;background:white;padding:10px;border-radius:4px;margin:10px 0;font-size:12px;color:#4CAF50">=SOMA(A1:A10)</code><p style="font-size:12px;color:#666;margin-top:8px">Use ":" para intervalos!</p></div></div></div></div>',
    
    6: '<div style="padding:20px;background:linear-gradient(135deg,#ffecd2,#fcb69f);border-radius:12px"><h3>📋 Prompt para Planilha Completa</h3><div style="background:white;padding:20px;border-radius:8px"><p style="margin-bottom:15px"><strong>IA pode criar planilhas inteiras do zero:</strong></p><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin:15px 0"><strong>Exemplo de prompt completo:</strong><div style="background:white;padding:12px;border-radius:4px;margin:10px 0;font-size:13px;color:#555">"Crie uma planilha de controle financeiro pessoal com:<br>• Colunas: Data, Categoria, Descrição, Entrada, Saída, Saldo<br>• Fórmulas automáticas para calcular o saldo<br>• Gráfico de pizza das despesas por categoria<br>• Formatação condicional (vermelho para saldo negativo)"</div></div><div style="padding:12px;background:#E8F5E9;border-left:4px solid #4CAF50;border-radius:4px"><strong>✅ Resultado:</strong> Planilha funcional e formatada em segundos!</div></div></div>',
    
    7: '<div style="padding:20px;background:linear-gradient(135deg,#667eea,#764ba2);border-radius:12px;color:white"><h3>⚠️ Limitações da IA no Excel</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>IA é poderosa, mas tem limites:</strong></p><ul style="padding-left:20px;font-size:14px;margin:15px 0"><li style="margin:8px 0">❌ Pode gerar fórmulas com pequenos erros</li><li style="margin:8px 0">❌ Não entende o contexto do seu negócio</li><li style="margin:8px 0">❌ Pode sugerir funções não disponíveis na sua versão</li><li style="margin:8px 0">❌ Não substitui conhecimento de Excel</li></ul><div style="padding:15px;background:#FFF3CD;border-left:4px solid #FFA000;border-radius:4px;margin-top:15px"><strong>💡 Use IA como assistente</strong>, mas sempre revise e teste os resultados!</div></div></div>',
    
    8: '<div style="padding:20px;background:linear-gradient(135deg,#f093fb,#f5576c);border-radius:12px;color:white"><h3>🔧 IA para Criar Macros VBA</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><p style="margin-bottom:15px"><strong>IA pode gerar código VBA automático:</strong></p><div style="background:#E3F2FD;padding:15px;border-radius:8px;margin:15px 0"><strong>Você pede:</strong><div style="background:white;padding:10px;border-radius:4px;margin:10px 0;font-size:13px">"Crie uma macro que formata a primeira linha como cabeçalho (negrito, cor de fundo azul, texto branco)"</div></div><div style="background:#f5f5f5;padding:15px;border-radius:8px;margin-top:15px"><strong>IA gera:</strong><code style="display:block;font-size:11px;font-family:monospace;margin-top:10px;color:#2196F3">Sub FormatarCabecalho()<br>&nbsp;&nbsp;Range("A1:Z1").Font.Bold = True<br>&nbsp;&nbsp;Range("A1:Z1").Interior.Color = RGB(0,0,255)<br>&nbsp;&nbsp;Range("A1:Z1").Font.Color = RGB(255,255,255)<br>End Sub</code></div></div></div>',
    
    9: '<div style="padding:20px;background:linear-gradient(135deg,#fa709a,#fee140);border-radius:12px;color:white"><h3>🛠️ Melhores Ferramentas de IA para Excel</h3><div style="background:white;padding:20px;border-radius:8px;color:#333"><div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:20px 0"><div style="padding:15px;background:#E3F2FD;border-radius:8px"><div style="font-size:32px;text-align:center;margin-bottom:10px">💬</div><strong>ChatGPT / Claude</strong><p style="font-size:12px;color:#666;margin-top:8px">Para gerar fórmulas e explicar conceitos</p></div><div style="padding:15px;background:#E8F5E9;border-radius:8px"><div style="font-size:32px;text-align:center;margin-bottom:10px">🤖</div><strong>Microsoft Copilot</strong><p style="font-size:12px;color:#666;margin-top:8px">Integrado no Excel 365</p></div><div style="padding:15px;background:#FFF3CD;border-radius:8px"><div style="font-size:32px;text-align:center;margin-bottom:10px">⚡</div><strong>Formula Bot</strong><p style="font-size:12px;color:#666;margin-top:8px">Especializado em fórmulas Excel</p></div><div style="padding:15px;background:#FCE4EC;border-radius:8px"><div style="font-size:32px;text-align:center;margin-bottom:10px">🎯</div><strong>SheetAI</strong><p style="font-size:12px;color:#666;margin-top:8px">Add-in com IA dentro do Excel</p></div></div></div></div>',
  },
};

async function main() {
  console.log('🎨 Adicionando contextos visuais finais...\n');
  let totalUpdated = 0;

  for (const [slug, questionsContexts] of Object.entries(finalContexts)) {
    const trail = await prisma.trails.findUnique({ where: { slug } });
    if (!trail) continue;

    console.log(`📚 ${trail.name}`);

    for (const [orderStr, htmlContext] of Object.entries(questionsContexts)) {
      const order = parseInt(orderStr);
      const question = await prisma.questions.findFirst({
        where: { trailId: trail.id, order }
      });

      if (!question) continue;

      let newContext = JSON.stringify({ htmlView: htmlContext });
      
      if (question.spreadsheetContext) {
        try {
          const existing = JSON.parse(question.spreadsheetContext);
          existing.htmlView = htmlContext;
          newContext = JSON.stringify(existing);
        } catch {}
      }

      await prisma.questions.update({
        where: { id: question.id },
        data: { spreadsheetContext: newContext },
      });
      
      totalUpdated++;
      process.stdout.write('✓');
    }
    console.log('  ✅\n');
  }

  console.log(`\n🎉 ${totalUpdated} contextos visuais adicionados!`);
  console.log(`\n📊 Total geral estimado: 70+ contextos visuais HTML completos!`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
